# NumPy Basics

NumPy (Numerical Python) is an open source library for the Python programming language that is used to facilitate scientific computing and data analysis. The library allows for improved performance over native Python code due to the fact that a large percentage of NumPy is written in C, and fewer explicit loops are used in operations overall. At the center of this package there lies the NumPy array in addition to the complementary mathematical functions and tools that allows users to work with these objects. A NumPy array, or ndarray, is a uniform and multidimensional collection of elements that can be used to describing blocks of computer memory for future manipulation. Being able to convert information into numerical representations is fundamental to data science, and this data structure allows for the efficient storage and management of numerical arrays.

More Information on NumPy: https://docs.scipy.org/doc/numpy-1.13.0/user/whatisnumpy.html


## Efficiency of NumPy Arrays

Adding Vectors (one-dimensional arrays)
- Vector a = Squares of integers from 0 to n
- Vector b = Cubes of integers from 0 to n

In [25]:
from datetime import datetime 
import numpy as np

# Adding vectors using pure Python
def sumWithPython(vectorSize):   
    a = list(range(vectorSize))  
    b = list(range(vectorSize))  
    c = []
    for i in list(range(len(a))):       
        a[i] = i ** 2       
        b[i] = i ** 3       
        c.append(a[i] + b[i])
    return c 

# Adding vectors using NumPy
def sumWithNumpy(vectorSize):   
    a = np.arange(vectorSize) ** 2   
    b = np.arange(vectorSize) ** 3   
    c = a + b
    return c

size = 1000000

startTime = datetime.now()
c = sumWithPython(size) 
pythonDelta = datetime.now() - startTime 
print("Pure Python elapsed time:", str(pythonDelta.microseconds), " microseconds")

startTime = datetime.now() 
c = sumWithNumpy(size) 
numpyDelta = datetime.now() - startTime 
print("NumPy elapsed time:", str(numpyDelta.microseconds), " microseconds")

Pure Python elapsed time: 106340  microseconds
NumPy elapsed time: 32581  microseconds


## Array creation, data types, and other attributes of ndarray

**Documentation: https://docs.scipy.org/doc/numpy-1.13.0/reference/**

In [26]:
# Import NumPy
import numpy as np

# Display NumPy's built-in documentation
# np?

# Create array
array = np.arange(10)

# Display its data type
array.dtype

dtype('int32')

In [27]:
# Display array
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# Display shape of array (one-dimensional)
array.shape

(10,)

In [29]:
# Create a two by five two-dimensional array
twoDimArray = np.arange(10).reshape((2, 5))
twoDimArray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
# 2x5 shape
twoDimArray.shape

(2, 5)

In [31]:
# Another way to create a multi-dimensional array
tda = np.array([np.arange(5), np.arange(5)]) 
print(tda)

# Display the shape of the array
tda.shape

[[0 1 2 3 4]
 [0 1 2 3 4]]


(2, 5)

**The array() function will create an array from the inputs so long as they are array-like objects.**

In [32]:
# View array() function documentation
# array?

In [33]:
# Create array from Python list
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [34]:
# Specify data type upon creation
x = np.array([1, 2, 3, 4, 5], dtype='float32')
print(x)
x.dtype

[1. 2. 3. 4. 5.]


dtype('float32')

In [35]:
# Creates an array that starts at 0 and ends at 100 going by 10
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
# Creates an array of ten values evenly spaced between 0 and 1
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [37]:
# Create a 5x5 array of random integers from 0 to 5
np.random.randint(0, 5, (5, 5))

array([[3, 4, 3, 1, 3],
       [1, 3, 3, 0, 0],
       [4, 0, 2, 0, 2],
       [2, 2, 4, 4, 3],
       [0, 1, 3, 2, 3]])

In [38]:
# Create a 10x5 array of normally distributed random values with a mean of 0 and standard deviation of 1
np.random.normal(0, 1, (10, 5))

array([[-0.75912251,  0.51297446,  0.26987208,  0.21508058,  0.75017378],
       [ 1.27150584, -0.59740167,  0.48767764, -0.53387883, -0.38768673],
       [-0.07151322, -0.52132965,  0.52198897, -0.58699079, -1.11940404],
       [ 0.95314079,  1.43165464,  0.5120382 , -1.97728554, -1.16689269],
       [-0.27643754,  0.39811053, -0.24823089,  1.41217947, -0.75093265],
       [ 2.59800325, -0.5050072 ,  0.92205687,  1.48540426,  2.67751231],
       [ 1.55312121,  1.05565036,  0.76712842,  0.45089139, -0.87153357],
       [-0.41409133,  1.00510306,  1.0148198 , -0.46372303, -1.62632692],
       [ 0.66605148, -1.29685507, -0.76276359,  0.38063723, -0.93959441],
       [ 0.59835732,  0.15882198,  0.76486361, -0.6097947 , -0.98004447]])

In [39]:
# Creating a three-dimensional array of two 5x5 arrays with random integer values from 0 through 9
threeDimArray = np.random.randint(10, size=(2, 5, 5)) 
threeDimArray

array([[[3, 1, 6, 7, 1],
        [7, 3, 2, 7, 8],
        [6, 3, 6, 4, 3],
        [3, 3, 4, 1, 6],
        [4, 5, 8, 8, 1]],

       [[1, 0, 2, 0, 7],
        [2, 3, 1, 3, 0],
        [2, 9, 8, 4, 2],
        [3, 1, 3, 2, 1],
        [1, 5, 6, 5, 5]]])

In [40]:
print("Array Attributes\n")
print("Number of dimensions:", threeDimArray.ndim)
print("Size of each dimension:", threeDimArray.shape)
print("Total size of array:", threeDimArray.size)
print("Size of each array element:", threeDimArray.itemsize, "bytes")
print("Total size (in bytes) of the array:", threeDimArray.nbytes, "bytes")

Array Attributes

Number of dimensions: 3
Size of each dimension: (2, 5, 5)
Total size of array: 50
Size of each array element: 4 bytes
Total size (in bytes) of the array: 200 bytes


In [41]:
# Reshaping array
print(threeDimArray.reshape(5, 10))

[[3 1 6 7 1 7 3 2 7 8]
 [6 3 6 4 3 3 3 4 1 6]
 [4 5 8 8 1 1 0 2 0 7]
 [2 3 1 3 0 2 9 8 4 2]
 [3 1 3 2 1 1 5 6 5 5]]


**More Information on array creation: https://docs.scipy.org/doc/numpy-1.13.0/user/basics.creation.html**

## Standard NumPy Data Types

| Type	        | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

**Reference: https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.01-Understanding-Data-Types.ipynb**

## Selecting Elements

**Documentation: https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html**

In [42]:
# 1D Array
x = np.array([1, 2, 3, 4])

# Display index one
print(x[1])

2


In [43]:
# 2D Array
x = np.array([[1, 2], 
              [3, 4]])

# Display element at certain indices
print(x[0, 0])
print(x[0, 1])
print(x[1, 0])
print(x[1, 1])

1
2
3
4


In [44]:
# 3D Array
x = np.random.randint(10, size=(3, 2, 2)) 

print(x, "\n")

# Display the first index of the second element in the 3rd array
print(x[2][1][0])

print(x
      [1] # 2nd array
      [0] # First element
      [1]) # Second index

[[[2 0]
  [7 1]]

 [[4 6]
  [7 2]]

 [[0 1]
  [4 5]]] 

4
6


## Subarrays

In [45]:
# 1D Array
x = np.arange(10)
print(x, "\n")

print("First two elements:\n", x[:2], "\n")

print("Elements after index 4 including index 4:\n", x[4:], "\n")

print("Elements between indices 2 and 4 but not including 4:\n", x[2:4], "\n")

print("Elements from index 2 to 7 by twos:\n", x[2:7:2], "\n")

print("Reverse array:\n", x[::-1], "\n")

[0 1 2 3 4 5 6 7 8 9] 

First two elements:
 [0 1] 

Elements after index 4 including index 4:
 [4 5 6 7 8 9] 

Elements between indices 2 and 4 but not including 4:
 [2 3] 

Elements from index 2 to 7 by twos:
 [2 4 6] 

Reverse array:
 [9 8 7 6 5 4 3 2 1 0] 



In [46]:
# 2D Array
x = np.random.randint(10, size=(4, 6))
print(x, "\n")

print("Two rows, four columns:\n", x[:2, :4], "\n")

print("First row:\n", x[0, :], "\n")

print("Third column:\n", x[:, 2], "\n")

print("Reverse array:\n", x[::-1, ::-1], "\n")

[[4 7 9 5 8 6]
 [9 1 3 2 3 0]
 [5 6 1 1 5 5]
 [4 5 9 6 4 4]] 

Two rows, four columns:
 [[4 7 9 5]
 [9 1 3 2]] 

First row:
 [4 7 9 5 8 6] 

Third column:
 [9 3 1 9] 

Reverse array:
 [[4 4 6 9 5 4]
 [5 5 1 1 6 5]
 [0 3 2 3 1 9]
 [6 8 5 9 7 4]] 



**Changing a value in a subarray will influence the parent array.**

In [47]:
print("Two rows, two columns sub array from x:\n", x[:2, :2], "\n")
xSub = x[:2, :2]

# Chnage element
xSub[0, 1] = 11
print(x)

Two rows, two columns sub array from x:
 [[4 7]
 [9 1]] 

[[ 4 11  9  5  8  6]
 [ 9  1  3  2  3  0]
 [ 5  6  1  1  5  5]
 [ 4  5  9  6  4  4]]


In [48]:
# 3D Array
x = np.arange(30).reshape(2, 3, 5) 
print(x, "\n")

print("Select every second elment from subarray x[0][0]:\n", x[0, 0, ::2], "\n")

print("Third column values from all 2D arrays (matrices):\n", x[..., 2], "\n")

print("Second row values from all 2D arrays (matrices):\n", x[:, 1], "\n")

print("First matrix, last column:\n", x[0, : ,-1], "\n")

print("Last matrix, first column reversed:\n", x[-1, :: -1, 0], "\n")

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] 

Select every second elment from subarray x[0][0]:
 [0 2 4] 

Third column values from all 2D arrays (matrices):
 [[ 2  7 12]
 [17 22 27]] 

Second row values from all 2D arrays (matrices):
 [[ 5  6  7  8  9]
 [20 21 22 23 24]] 

First matrix, last column:
 [ 4  9 14] 

Last matrix, first column reversed:
 [25 20 15] 



**Copying an array.**

In [49]:
xSubCopy = x[:2, :2, :3].copy()
print(xSubCopy, "\n")

# Change element
xSubCopy[0][0][0] = 11
print(xSubCopy, "\n")

# No influence on original
print(x, "\n")

[[[ 0  1  2]
  [ 5  6  7]]

 [[15 16 17]
  [20 21 22]]] 

[[[11  1  2]
  [ 5  6  7]]

 [[15 16 17]
  [20 21 22]]] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] 



## Array Reshaping

**Documentation: https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html**

In [50]:
threeDimArray = np.random.randint(10, size=(4, 4, 4)) 
print(threeDimArray, "\n")

# Reshaping array
print(threeDimArray.reshape(8, 8), "\n")

[[[1 4 7 0]
  [2 7 5 3]
  [7 8 9 1]
  [8 5 0 7]]

 [[9 9 0 9]
  [2 3 3 6]
  [1 5 1 4]
  [3 8 1 6]]

 [[9 7 3 5]
  [8 4 9 7]
  [9 4 0 5]
  [9 4 8 2]]

 [[7 3 1 1]
  [5 8 1 0]
  [3 1 6 5]
  [8 8 1 6]]] 

[[1 4 7 0 2 7 5 3]
 [7 8 9 1 8 5 0 7]
 [9 9 0 9 2 3 3 6]
 [1 5 1 4 3 8 1 6]
 [9 7 3 5 8 4 9 7]
 [9 4 0 5 9 4 8 2]
 [7 3 1 1 5 8 1 0]
 [3 1 6 5 8 8 1 6]] 



In [51]:
# Other ways to reshape
# These modifiy the array they operate on
x = np.random.randint(10, size=(2, 4, 4)) 
print(x, "\n")

x.shape = (4, 8)
print("Shape:\n", x, "\n")

y = np.random.randint(10, size=(2, 3, 2)) 
print(y, "\n")

y.resize((2, 6))
print("Resize:\n", y)

[[[8 1 1 9]
  [5 7 0 5]
  [2 7 9 2]
  [2 5 8 5]]

 [[6 4 6 1]
  [0 5 2 8]
  [6 0 3 7]
  [3 2 3 5]]] 

Shape:
 [[8 1 1 9 5 7 0 5]
 [2 7 9 2 2 5 8 5]
 [6 4 6 1 0 5 2 8]
 [6 0 3 7 3 2 3 5]] 

[[[4 3]
  [4 9]
  [4 2]]

 [[2 1]
  [0 9]
  [6 8]]] 

Resize:
 [[4 3 4 9 4 2]
 [2 1 0 9 6 8]]


**Flattening a multidimensional NumPy arrays results in a one-dimensional array.**

In [52]:
x = np.random.randint(10, size=(3, 3, 3)) 
print(x)

[[[3 7 1]
  [1 2 8]
  [7 1 3]]

 [[3 2 8]
  [3 1 2]
  [0 8 4]]

 [[9 3 3]
  [3 2 3]
  [6 7 1]]]


In [53]:
print(np.ravel(x))

[3 7 1 1 2 8 7 1 3 3 2 8 3 1 2 0 8 4 9 3 3 3 2 3 6 7 1]


**The flatten function does the same as ravel, but it always creates a new copy in memory in order to avoid modifying the original array.**

In [54]:
x = np.random.randint(10, size=(2, 2, 2)) 
print(x.flatten())

[9 4 5 8 2 3 8 4]


## Stacking

**Documentation: https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html**

**Horizontal stacking of arrays.**

In [55]:
x = np.random.randint(10, size=(3, 3)) 
y = x - 1

# Stacks arrays horizontally 
z = np.hstack((x, y))
print(x, "\n")
print(y, "\n")
print(z)

# concatenate((x, y), axis=1) does the same thing

[[9 2 0]
 [5 1 7]
 [3 7 2]] 

[[ 8  1 -1]
 [ 4  0  6]
 [ 2  6  1]] 

[[ 9  2  0  8  1 -1]
 [ 5  1  7  4  0  6]
 [ 3  7  2  2  6  1]]


**Vertical stacking of arrays.**

In [56]:
x = np.random.randint(10, size=(3, 3)) 
y = x - 1

# Stacks arrays vertically 
z = np.vstack((x, y))
print(x, "\n")
print(y, "\n")
print(z)

# concatenate((x, y), axis=0) does the same thing

[[1 8 4]
 [0 7 7]
 [1 6 0]] 

[[ 0  7  3]
 [-1  6  6]
 [ 0  5 -1]] 

[[ 1  8  4]
 [ 0  7  7]
 [ 1  6  0]
 [ 0  7  3]
 [-1  6  6]
 [ 0  5 -1]]


**Depth stacking of arrays.**

In [57]:
x = np.random.randint(10, size=(3, 3)) 
y = x - 1

# Stacks arrays depth-wise along the third axis 
z = np.dstack((x, y))
print(x, "\n")
print(y, "\n")
print(z)

[[8 8 8]
 [4 4 9]
 [9 9 1]] 

[[7 7 7]
 [3 3 8]
 [8 8 0]] 

[[[8 7]
  [8 7]
  [8 7]]

 [[4 3]
  [4 3]
  [9 8]]

 [[9 8]
  [9 8]
  [1 0]]]


**Column stacking of arrays.**

In [58]:
x = np.random.randint(10, size=(10)) 
y = x + 1

# Stacks one-dimensional arrays as columns to create a two-dimensional array 
z = np.column_stack((x, y))
print(x, "\n")
print(y, "\n")
print(z)

# Two-dimensional arrays are stacked in the same way that hstack stacks them

[8 1 2 8 4 2 6 3 5 4] 

[9 2 3 9 5 3 7 4 6 5] 

[[8 9]
 [1 2]
 [2 3]
 [8 9]
 [4 5]
 [2 3]
 [6 7]
 [3 4]
 [5 6]
 [4 5]]


In [59]:
x = np.random.randint(10, size=(10)) 
y = x + 1

# Stacks one-dimensional arrays as rows to create a two-dimensional array 
z = np.row_stack((x, y))
print(x, "\n")
print(y, "\n")
print(z)

# Two-dimensional arrays are stacked in the same way that vstack stacks them

[4 2 2 0 4 4 0 0 8 0] 

[5 3 3 1 5 5 1 1 9 1] 

[[4 2 2 0 4 4 0 0 8 0]
 [5 3 3 1 5 5 1 1 9 1]]


## Splitting

**Documentation: https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.split.html**

**Horizontal splitting**

In [60]:
x = np.random.randint(10, size=(3, 4)) 
print(x, "\n")

# Splits the array along its horizontal axis into n pieces of the same size and shape
print(np.hsplit(x, 2))

[[7 6 7 0]
 [9 7 3 6]
 [0 5 5 8]] 

[array([[7, 6],
       [9, 7],
       [0, 5]]), array([[7, 0],
       [3, 6],
       [5, 8]])]


**Vertical splitting**

In [61]:
x = np.random.randint(10, size=(3, 6)) 
print(x, "\n")

# Splits the array along its vertical axis into n pieces of the same size and shape
print(np.vsplit(x, 3))

[[4 4 1 2 4 7]
 [8 8 1 5 5 2]
 [0 6 8 3 0 0]] 

[array([[4, 4, 1, 2, 4, 7]]), array([[8, 8, 1, 5, 5, 2]]), array([[0, 6, 8, 3, 0, 0]])]


**Depth-wise splitting**

In [62]:
x = np.random.randint(10, size=(2, 3, 4)) 
print(x, "\n")

# Splits the array depth-wise along the third axis into n pieces of the same size and shape
print(np.dsplit(x, 4))

[[[8 7 0 4]
  [9 9 9 7]
  [9 3 2 0]]

 [[8 3 5 1]
  [4 3 7 9]
  [8 1 8 4]]] 

[array([[[8],
        [9],
        [9]],

       [[8],
        [4],
        [8]]]), array([[[7],
        [9],
        [3]],

       [[3],
        [3],
        [1]]]), array([[[0],
        [9],
        [2]],

       [[5],
        [7],
        [8]]]), array([[[4],
        [7],
        [0]],

       [[1],
        [9],
        [4]]])]


## Converting Arrays

In [63]:
x = np.random.randint(10, size=(5)) 
print(x)

# Convert to single precision float
f = x.astype(np.float32)
print(f)

# Convert to string
s = x.astype(np.str)
print(s)

# Convert to complex number
c = x.astype(np.complex)
print(c)

[8 0 4 7 9]
[8. 0. 4. 7. 9.]
['8' '0' '4' '7' '9']
[8.+0.j 0.+0.j 4.+0.j 7.+0.j 9.+0.j]


## Statistical Functions

**Documentation: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.statistics.html**

In [64]:
import numpy as np

# Loads the data from sample_data.csv into an array
# Stops at close price
data=np.loadtxt('sample_data.csv', delimiter=',', usecols=(6,), unpack=True)

# Computes the median
print("Median:", np.median(data))

# Computes the mean
print("Mean:", np.mean(data))

# Computes the average
print("Average:", np.average(data))

# Computes the variance
print("Variance:", np.var(data))

# Returns the minimum value
print("Minimum:", np.amin(data))

# Returns the maximum value
print("Maximum:", np.amax(data))

Median: 352.055
Mean: 351.0376666666667
Average: 351.0376666666667
Variance: 50.126517888888884
Minimum: 336.1
Maximum: 363.13


### Stock Returns

**Simple stock returns can be obtained by finding the rate of change from one value to the next. The rate of change for logarithmic returns can be found with:**

$$log(p_{i})-log(p_{j})=log\left({p_{i}\over p_{j}}\right)$$

**More Information: https://quantivity.wordpress.com/2011/02/21/why-log-returns/**

In [65]:
data = np.loadtxt('sample_data.csv', delimiter=',', usecols=(6,), unpack=True)

# Calculate returns by obtaining the difference between two successive array elements
# and dividing by the previous value
returns = np.diff(data) / data[ : -1] # Resulting diff() array is one element short of the close prices array
print("Standard deviation:", np.std(returns))

# Calculates the natural logarithm of the close prices then the differences 
logarithmicReturns = np.diff(np.log(data))

# Returns a tuple that contains the indices that indicate a positive return
positiveIndices = np.where(returns > 0)
print("Indices with positive returns:", positiveIndices)

# Volatility measures the price variation of a financial security
# Historical price data (logarithmic returns) can be used to calculate historical volatility
annualVolatility = np.std(logarithmicReturns) / np.mean(logarithmicReturns)
annualVolatility = annualVolatility / np.sqrt(1. / 252.)

print("Annual Volatility:", annualVolatility)

print("Monthly Volatility:", annualVolatility * np.sqrt(1. / 12.))

Standard deviation: 0.012922134436826306
Indices with positive returns: (array([ 0,  1,  4,  5,  6,  7,  9, 10, 11, 12, 16, 17, 18, 19, 21, 22, 23,
       25, 28], dtype=int64),)
Annual Volatility: 129.27478991115132
Monthly Volatility: 37.318417377317765


## References
> Idris, I. (2015). NumPy Beginner's Guide (3rd ed.). Birmingham, United Kingdom: Packt Publishing.

> Quantivity. (2011, February 21). Why Log Returns. Retrieved from quantivity.wordpress.com: 
https://quantivity.wordpress.com/2011/02/21/why-log-returns/

> SciPy Community. (2017, June 10). Array creation, 1.13. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy-1.13.0/user/basics.creation.html

> SciPy Community. (2017, June 10). Indexing, 1.13. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html

> SciPy Community. (2017, June 10). NumPy Reference, 1.13. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy-1.13.0/reference/

> SciPy Community. (2017, June 10). Statistics, 1.13. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.statistics.html

> SciPy Community. (2017, June 10). What is NumPy?, 1.13. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy-1.13.0/user/whatisnumpy.html

> SciPy Community. (2018, January 8). numpy.concatenate, 1.14. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

> SciPy Community. (2018, January 8). numpy.reshape, 1.14. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

> SciPy Community. (2018, January 8). numpy.split, 1.14. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.split.html

> VanderPlas, J. (2016). Python Data Science Handbook (1st ed.). Sebastopol, California, United States of America: O’Reilly Media.

> VanderPlas, J. (2017, Junuary 5). Understanding Data Types in Python. Retrieved from github.com: https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.01-Understanding-Data-Types.ipynb