# NumPy Basics

NumPy (Numerical Python) is an open source library for the Python programming language that is used to facilitate scientific computing and data analysis. The library allows for improved performance over native Python code due to the fact that a large percentage of NumPy is written in C, and fewer explicit loops are used in operations overall. At the center of this package there lies the NumPy array in addition to the complementary mathematical functions and tools that allows users to work with these objects. A NumPy array, or ndarray, is a uniform and multidimensional collection of elements that can be used to describing blocks of computer memory for future manipulation. Being able to convert information into numerical representations is fundamental to data science, and this data structure allows for the efficient storage and management of numerical arrays.

More Information on NumPy: https://docs.scipy.org/doc/numpy-1.14.0/user/whatisnumpy.html

## Efficiency of NumPy Arrays

Adding Vectors (one-dimensional arrays)
- Vector a = Squares of integers from 0 to n
- Vector b = Cubes of integers from 0 to n

In [162]:
from datetime import datetime 
import numpy as np

# Adding vectors using pure Python
def sumWithPython(vectorSize):   
    a = list(range(vectorSize))  
    b = list(range(vectorSize))  
    c = []
    for i in list(range(len(a))):       
        a[i] = i ** 2       
        b[i] = i ** 3       
        c.append(a[i] + b[i])
    return c 

# Adding vectors using NumPy
def sumWithNumpy(vectorSize):   
    a = np.arange(vectorSize) ** 2   
    b = np.arange(vectorSize) ** 3   
    c = a + b
    return c

size = 1000000

startTime = datetime.now()
c = sumWithPython(size) 
pythonDelta = datetime.now() - startTime 
print("Pure Python elapsed time:", str(pythonDelta.microseconds), " microseconds")

startTime = datetime.now() 
c = sumWithNumpy(size) 
numpyDelta = datetime.now() - startTime 
print("NumPy elapsed time:", str(numpyDelta.microseconds), " microseconds")

Pure Python elapsed time: 109248  microseconds
NumPy elapsed time: 46058  microseconds


## Array creation, data types, and other attributes of ndarray

**Documentation: https://docs.scipy.org/doc/numpy-1.14.0/reference/index.html**

In [163]:
# Import NumPy
import numpy as np

# Display NumPy's built-in documentation.
# np?

# Create an array.
array = np.arange(10)

# Display its data type.
array.dtype

dtype('int32')

In [164]:
# Display array.
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
# Display shape of array (one-dimensional).
array.shape

(10,)

In [166]:
# Create a two by five two-dimensional array.
twoDimArray = np.arange(10).reshape((2, 5))
twoDimArray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [167]:
# 2x5 shape
twoDimArray.shape

(2, 5)

In [168]:
# Another way to create a multi-dimensional array.
tda = np.array([np.arange(5), np.arange(5)]) 
print(tda)

# Display the shape of the array.
tda.shape

[[0 1 2 3 4]
 [0 1 2 3 4]]


(2, 5)

**The array() function will create an array from the inputs so long as they are array-like objects.**

In [169]:
# View array() function documentation
# array?

In [170]:
# Create array from Python list.
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [171]:
# Specify data type upon creation.
x = np.array([1, 2, 3, 4, 5], dtype='float32')
print(x)
x.dtype

[1. 2. 3. 4. 5.]


dtype('float32')

In [172]:
# Creates an array that starts at 0 and ends at 100 going by 10.
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [173]:
# Creates an array of ten values evenly spaced between 0 and 1.
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [174]:
# Create a 5x5 array of random integers from 0 to 5.
np.random.randint(0, 5, (5, 5))

array([[1, 2, 2, 4, 0],
       [1, 4, 4, 3, 1],
       [2, 2, 4, 0, 4],
       [3, 2, 2, 1, 1],
       [2, 1, 3, 3, 0]])

In [175]:
# Create a 10x5 array of normally distributed random values with a mean of 0 and standard deviation of 1.
np.random.normal(0, 1, (10, 5))

array([[-1.5263535 ,  0.95769227, -0.64439337, -0.33884374, -0.50790793],
       [ 1.29051123,  2.09399953,  1.17231208,  1.2146431 , -0.48548899],
       [ 0.00986596, -0.48109211, -0.39999843, -0.45388237,  0.30274371],
       [ 0.15593379,  1.09698043, -1.13820226, -0.27714674, -0.90512326],
       [-2.10062543, -1.94215049, -0.93516655,  0.65370888, -0.56461481],
       [-1.23414128,  0.43355438,  0.16492617, -1.18735162,  0.42943835],
       [ 0.67909232,  0.39775604, -0.26164618, -0.42964638,  2.00648395],
       [-0.41362618,  0.14898142, -0.29176936, -0.60358076,  2.40216644],
       [ 0.38028284,  0.44897653, -0.97568817, -0.13850516,  1.44084981],
       [ 1.28434622,  0.5106246 , -0.43228005, -0.21144603, -1.01512728]])

In [176]:
# Creating a three-dimensional array of two 5x5 arrays with random integer values from 0 through 9.
threeDimArray = np.random.randint(10, size=(2, 5, 5)) 
threeDimArray

array([[[4, 8, 7, 1, 7],
        [7, 4, 1, 6, 0],
        [3, 0, 0, 6, 2],
        [0, 8, 0, 1, 5],
        [2, 6, 0, 1, 8]],

       [[8, 3, 6, 4, 0],
        [3, 7, 3, 5, 2],
        [0, 2, 0, 6, 2],
        [4, 4, 0, 1, 8],
        [5, 1, 1, 0, 9]]])

In [177]:
print("Array Attributes\n")
print("Number of dimensions:", threeDimArray.ndim)
print("Size of each dimension:", threeDimArray.shape)
print("Total size of array:", threeDimArray.size)
print("Size of each array element:", threeDimArray.itemsize, "bytes")
print("Total size (in bytes) of the array:", threeDimArray.nbytes, "bytes")

Array Attributes

Number of dimensions: 3
Size of each dimension: (2, 5, 5)
Total size of array: 50
Size of each array element: 4 bytes
Total size (in bytes) of the array: 200 bytes


In [178]:
# Reshaping array.
print(threeDimArray.reshape(5, 10))

[[4 8 7 1 7 7 4 1 6 0]
 [3 0 0 6 2 0 8 0 1 5]
 [2 6 0 1 8 8 3 6 4 0]
 [3 7 3 5 2 0 2 0 6 2]
 [4 4 0 1 8 5 1 1 0 9]]


**More Information on array creation: https://docs.scipy.org/doc/numpy-1.14.0/user/basics.creation.html**

## Standard NumPy Data Types

| Type	        | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

**Reference: https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.01-Understanding-Data-Types.ipynb**

## Selecting Elements

**Documentation: https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.indexing.html**

In [179]:
# 1D Array
x = np.array([1, 2, 3, 4])

# Display index one.
print(x[1])

2


In [180]:
# 2D Array
x = np.array([[1, 2], 
              [3, 4]])

# Display element at certain indices.
print(x[0, 0])
print(x[0, 1])
print(x[1, 0])
print(x[1, 1])

1
2
3
4


In [181]:
# 3D Array
x = np.random.randint(10, size=(3, 2, 2)) 

print(x, "\n")

# Display the first index of the second element in the 3rd array.
print(x[2][1][0])

print(x
      [1] # 2nd array
      [0] # First element
      [1]) # Second index

[[[2 8]
  [8 3]]

 [[9 9]
  [8 7]]

 [[5 9]
  [8 9]]] 

8
9


## Subarrays

In [182]:
# 1D Array
x = np.arange(10)
print(x, "\n")

print("First two elements:\n", x[:2], "\n")

print("Elements after index 4 including index 4:\n", x[4:], "\n")

print("Elements between indices 2 and 4 but not including 4:\n", x[2:4], "\n")

print("Elements from index 2 to 7 by twos:\n", x[2:7:2], "\n")

print("Reverse array:\n", x[::-1], "\n")

[0 1 2 3 4 5 6 7 8 9] 

First two elements:
 [0 1] 

Elements after index 4 including index 4:
 [4 5 6 7 8 9] 

Elements between indices 2 and 4 but not including 4:
 [2 3] 

Elements from index 2 to 7 by twos:
 [2 4 6] 

Reverse array:
 [9 8 7 6 5 4 3 2 1 0] 



In [183]:
# 2D Array
x = np.random.randint(10, size=(4, 6))
print(x, "\n")

print("Two rows, four columns:\n", x[:2, :4], "\n")

print("First row:\n", x[0, :], "\n")

print("Third column:\n", x[:, 2], "\n")

print("Reverse array:\n", x[::-1, ::-1], "\n")

[[4 3 3 4 4 8]
 [5 7 3 7 9 4]
 [0 8 9 1 5 9]
 [9 2 6 4 6 0]] 

Two rows, four columns:
 [[4 3 3 4]
 [5 7 3 7]] 

First row:
 [4 3 3 4 4 8] 

Third column:
 [3 3 9 6] 

Reverse array:
 [[0 6 4 6 2 9]
 [9 5 1 9 8 0]
 [4 9 7 3 7 5]
 [8 4 4 3 3 4]] 



**Changing a value in a subarray will influence the parent array.**

In [184]:
print("Two rows, two columns sub array from x:\n", x[:2, :2], "\n")
xSub = x[:2, :2]

# Change element
xSub[0, 1] = 11
print(x)

Two rows, two columns sub array from x:
 [[4 3]
 [5 7]] 

[[ 4 11  3  4  4  8]
 [ 5  7  3  7  9  4]
 [ 0  8  9  1  5  9]
 [ 9  2  6  4  6  0]]


In [185]:
# 3D Array
x = np.arange(30).reshape(2, 3, 5) 
print(x, "\n")

print("Select every second elment from subarray x[0][0]:\n", x[0, 0, ::2], "\n")

print("Third column values from all 2D arrays (matrices):\n", x[..., 2], "\n")

print("Second row values from all 2D arrays (matrices):\n", x[:, 1], "\n")

print("First matrix, last column:\n", x[0, : ,-1], "\n")

print("Last matrix, first column reversed:\n", x[-1, :: -1, 0], "\n")

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] 

Select every second elment from subarray x[0][0]:
 [0 2 4] 

Third column values from all 2D arrays (matrices):
 [[ 2  7 12]
 [17 22 27]] 

Second row values from all 2D arrays (matrices):
 [[ 5  6  7  8  9]
 [20 21 22 23 24]] 

First matrix, last column:
 [ 4  9 14] 

Last matrix, first column reversed:
 [25 20 15] 



**Copying an array.**

In [186]:
xSubCopy = x[:2, :2, :3].copy()
print(xSubCopy, "\n")

# Change element
xSubCopy[0][0][0] = 11
print(xSubCopy, "\n")

# No influence on original
print(x, "\n")

[[[ 0  1  2]
  [ 5  6  7]]

 [[15 16 17]
  [20 21 22]]] 

[[[11  1  2]
  [ 5  6  7]]

 [[15 16 17]
  [20 21 22]]] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] 



## Array Reshaping

**Documentation: https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html**

In [187]:
threeDimArray = np.random.randint(10, size=(4, 4, 4)) 
print(threeDimArray, "\n")

# Reshaping array.
print(threeDimArray.reshape(8, 8), "\n")

[[[9 5 4 1]
  [4 6 5 9]
  [7 8 4 7]
  [7 7 8 5]]

 [[8 3 4 0]
  [9 1 7 9]
  [4 5 0 0]
  [4 8 0 4]]

 [[0 4 7 6]
  [7 7 6 9]
  [2 8 6 2]
  [2 7 5 2]]

 [[4 3 0 6]
  [7 0 0 1]
  [1 8 0 8]
  [8 3 9 5]]] 

[[9 5 4 1 4 6 5 9]
 [7 8 4 7 7 7 8 5]
 [8 3 4 0 9 1 7 9]
 [4 5 0 0 4 8 0 4]
 [0 4 7 6 7 7 6 9]
 [2 8 6 2 2 7 5 2]
 [4 3 0 6 7 0 0 1]
 [1 8 0 8 8 3 9 5]] 



In [188]:
# Other ways to reshape:
# These modifiy the array they operate on.
x = np.random.randint(10, size=(2, 4, 4)) 
print(x, "\n")

x.shape = (4, 8)
print("Shape:\n", x, "\n")

y = np.random.randint(10, size=(2, 3, 2)) 
print(y, "\n")

y.resize((2, 6))
print("Resize:\n", y)

[[[7 5 3 6]
  [4 4 6 8]
  [7 3 7 2]
  [1 2 2 1]]

 [[1 5 2 4]
  [4 6 6 2]
  [8 2 3 9]
  [6 8 8 9]]] 

Shape:
 [[7 5 3 6 4 4 6 8]
 [7 3 7 2 1 2 2 1]
 [1 5 2 4 4 6 6 2]
 [8 2 3 9 6 8 8 9]] 

[[[2 8]
  [4 0]
  [3 8]]

 [[4 9]
  [3 0]
  [7 8]]] 

Resize:
 [[2 8 4 0 3 8]
 [4 9 3 0 7 8]]


**Flattening a multidimensional NumPy arrays results in a one-dimensional array.**

In [189]:
x = np.random.randint(10, size=(3, 3, 3)) 
print(x)

[[[4 3 6]
  [2 7 5]
  [5 0 7]]

 [[6 7 4]
  [6 7 3]
  [7 5 2]]

 [[8 8 2]
  [5 1 2]
  [4 7 3]]]


In [190]:
print(np.ravel(x))

[4 3 6 2 7 5 5 0 7 6 7 4 6 7 3 7 5 2 8 8 2 5 1 2 4 7 3]


**The flatten function does the same as ravel, but it always creates a new copy in memory in order to avoid modifying the original array.**

In [191]:
x = np.random.randint(10, size=(2, 2, 2)) 
print(x.flatten())

[9 6 8 3 0 6 3 4]


## Stacking

**Documentation: https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html**

**Horizontal stacking of arrays.**

In [192]:
x = np.random.randint(10, size=(3, 3)) 
y = x - 1

# Stacks arrays horizontally. 
z = np.hstack((x, y))
print(x, "\n")
print(y, "\n")
print(z)

# concatenate((x, y), axis=1) does the same thing

[[5 8 8]
 [1 1 6]
 [8 7 0]] 

[[ 4  7  7]
 [ 0  0  5]
 [ 7  6 -1]] 

[[ 5  8  8  4  7  7]
 [ 1  1  6  0  0  5]
 [ 8  7  0  7  6 -1]]


**Vertical stacking of arrays.**

In [193]:
x = np.random.randint(10, size=(3, 3)) 
y = x - 1

# Stacks arrays vertically. 
z = np.vstack((x, y))
print(x, "\n")
print(y, "\n")
print(z)

# concatenate((x, y), axis=0) does the same thing

[[9 2 6]
 [4 9 8]
 [8 5 2]] 

[[8 1 5]
 [3 8 7]
 [7 4 1]] 

[[9 2 6]
 [4 9 8]
 [8 5 2]
 [8 1 5]
 [3 8 7]
 [7 4 1]]


**Depth stacking of arrays.**

In [194]:
x = np.random.randint(10, size=(3, 3)) 
y = x - 1

# Stacks arrays depth-wise along the third axis.
z = np.dstack((x, y))
print(x, "\n")
print(y, "\n")
print(z)

[[4 9 4]
 [6 1 2]
 [1 9 4]] 

[[3 8 3]
 [5 0 1]
 [0 8 3]] 

[[[4 3]
  [9 8]
  [4 3]]

 [[6 5]
  [1 0]
  [2 1]]

 [[1 0]
  [9 8]
  [4 3]]]


**Column stacking of arrays.**

In [195]:
x = np.random.randint(10, size=(10)) 
y = x + 1

# Stacks one-dimensional arrays as columns to create a two-dimensional array.
z = np.column_stack((x, y))
print(x, "\n")
print(y, "\n")
print(z)

# Two-dimensional arrays are stacked in the same way that hstack stacks them.

[5 5 0 3 2 3 1 9 8 9] 

[ 6  6  1  4  3  4  2 10  9 10] 

[[ 5  6]
 [ 5  6]
 [ 0  1]
 [ 3  4]
 [ 2  3]
 [ 3  4]
 [ 1  2]
 [ 9 10]
 [ 8  9]
 [ 9 10]]


In [196]:
x = np.random.randint(10, size=(10)) 
y = x + 1

# Stacks one-dimensional arrays as rows to create a two-dimensional array .
z = np.row_stack((x, y))
print(x, "\n")
print(y, "\n")
print(z)

# Two-dimensional arrays are stacked in the same way that vstack stacks them.

[2 7 1 1 6 2 4 1 3 5] 

[3 8 2 2 7 3 5 2 4 6] 

[[2 7 1 1 6 2 4 1 3 5]
 [3 8 2 2 7 3 5 2 4 6]]


## Splitting

**Documentation: https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.split.html**

**Horizontal splitting**

In [197]:
x = np.random.randint(10, size=(3, 4)) 
print(x, "\n")

# Splits the array along its horizontal axis into n pieces of the same size and shape.
print(np.hsplit(x, 2))

[[8 2 2 8]
 [1 4 4 9]
 [5 5 3 0]] 

[array([[8, 2],
       [1, 4],
       [5, 5]]), array([[2, 8],
       [4, 9],
       [3, 0]])]


**Vertical splitting**

In [198]:
x = np.random.randint(10, size=(3, 6)) 
print(x, "\n")

# Splits the array along its vertical axis into n pieces of the same size and shape.
print(np.vsplit(x, 3))

[[1 7 6 9 7 9]
 [7 2 0 9 8 3]
 [9 4 0 3 9 6]] 

[array([[1, 7, 6, 9, 7, 9]]), array([[7, 2, 0, 9, 8, 3]]), array([[9, 4, 0, 3, 9, 6]])]


**Depth-wise splitting**

In [199]:
x = np.random.randint(10, size=(2, 3, 4)) 
print(x, "\n")

# Splits the array depth-wise along the third axis into n pieces of the same size and shape.
print(np.dsplit(x, 4))

[[[6 2 6 4]
  [1 4 1 5]
  [2 3 5 2]]

 [[1 2 5 2]
  [7 0 9 2]
  [9 6 2 9]]] 

[array([[[6],
        [1],
        [2]],

       [[1],
        [7],
        [9]]]), array([[[2],
        [4],
        [3]],

       [[2],
        [0],
        [6]]]), array([[[6],
        [1],
        [5]],

       [[5],
        [9],
        [2]]]), array([[[4],
        [5],
        [2]],

       [[2],
        [2],
        [9]]])]


## Converting Arrays

In [200]:
x = np.random.randint(10, size=(5)) 
print(x)

# Convert to single precision float.
f = x.astype(np.float32)
print(f)

# Convert to string.
s = x.astype(np.str)
print(s)

# Convert to complex number.
c = x.astype(np.complex)
print(c)

[7 3 9 6 6]
[7. 3. 9. 6. 6.]
['7' '3' '9' '6' '6']
[7.+0.j 3.+0.j 9.+0.j 6.+0.j 6.+0.j]


## Statistical Functions

**Documentation: https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.statistics.html**

**Documentation: https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.loadtxt.html**

In [201]:
import numpy as np

# Loads the data from sample_data.csv into an array.
# Skips the first row and uses the closing price column.
data = np.loadtxt('tesla_sample_data.csv', delimiter=',', skiprows=1, usecols=4, unpack=True)

# Computes the median
print("Median:", np.median(data))

# Computes the mean
print("Mean:", np.mean(data))

# Computes the average
print("Average:", np.average(data))

# Computes the variance
print("Variance:", np.var(data))

# Returns the minimum value
print("Minimum:", np.amin(data))

# Returns the maximum value
print("Maximum:", np.amax(data))

Median: 188.64
Mean: 153.3023215230037
Average: 153.3023215230037
Variance: 11737.12610169673
Minimum: 15.8
Maximum: 385.0


### Stock Returns

**Simple stock returns can be obtained by finding the rate of change from one value to the next. The rate of change for logarithmic returns can be found with:**

$$log(p_{i})-log(p_{j})=log\left({p_{i}\over p_{j}}\right)$$

**More Information: https://quantivity.wordpress.com/2011/02/21/why-log-returns/**

In [202]:
data = np.loadtxt('tesla_sample_data.csv', delimiter=',', skiprows=1, usecols=4, unpack=True)

# Calculate returns by obtaining the difference between two successive array elements
# and dividing by the previous value.
returns = np.diff(data) / data[ : -1] # Resulting diff() array is one element short of the close prices array
print("Standard deviation:", np.std(returns), '\n')

# Returns a tuple that contains the indices that indicate a positive return.
positiveIndices = np.where(returns > 0)
print("Indices with positive returns:", positiveIndices, '\n')

# Calculates the natural logarithm of the close prices then the differences.
logarithmicReturns = np.diff(np.log(data))

# Volatility measures the price variation of a financial security.
# Historical price data (logarithmic returns) can be used to calculate historical volatility.
annualVolatility = np.std(logarithmicReturns) / np.mean(logarithmicReturns)
annualVolatility = annualVolatility / np.sqrt(1. / 252.) # There are around 252 trading days in a year

print("Annual Volatility:", annualVolatility, '\n')

print("Monthly Volatility:", annualVolatility * np.sqrt(1. / 12.), '\n')

Standard deviation: 0.03199734404234775 

Indices with positive returns: (array([   5,    8,    9,   10,   11,   12,   15,   16,   19,   22,   23,
         27,   31,   32,   33,   35,   36,   37,   39,   42,   44,   45,
         48,   51,   52,   53,   56,   60,   61,   62,   63,   65,   66,
         67,   73,   74,   78,   79,   81,   82,   84,   85,   88,   89,
         91,   93,   95,   96,   99,  100,  101,  102,  103,  106,  111,
        112,  117,  118,  119,  120,  121,  122,  125,  126,  128,  130,
        131,  132,  133,  134,  142,  143,  144,  145,  146,  148,  150,
        154,  156,  157,  160,  165,  166,  167,  168,  169,  170,  171,
        174,  176,  181,  184,  185,  186,  187,  188,  190,  193,  195,
        199,  200,  201,  203,  204,  205,  207,  208,  209,  215,  216,
        217,  219,  223,  224,  228,  229,  230,  231,  233,  234,  238,
        239,  240,  241,  246,  248,  251,  252,  253,  255,  257,  261,
        265,  266,  267,  268,  272,  274,  276,  

## References
> Idris, I. (2015). NumPy Beginner's Guide (3rd ed.). Birmingham, United Kingdom: Packt Publishing.

> Quantivity. (2011, February 21). Why Log Returns. Retrieved from quantivity.wordpress.com: https://quantivity.wordpress.com/2011/02/21/why-log-returns/

> SciPy Community. (2018, January 8). Array creation, 1.14. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy-1.14.0/user/basics.creation.html

> SciPy Community. (2018, January 8). Indexing, 1.14. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.indexing.html

> SciPy Community. (2018, January 8). NumPy Reference, 1.14. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy-1.14.0/reference/index.html

> SciPy Community. (2018, January 8). numpy.concatenate, 1.14. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

> SciPy Community. (2018, January 8). numpy.loadtxt, 1.14. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.loadtxt.html

> SciPy Community. (2018, January 8). numpy.reshape, 1.14. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

> SciPy Community. (2018, January 8). numpy.split, 1.14. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.split.html

> SciPy Community. (2018, January 8). Statistics, 1.14. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.statistics.html

> SciPy Community. (2018, January 8). What is NumPy?, 1.14. Retrieved from docs.scipy.org: https://docs.scipy.org/doc/numpy-1.14.0/user/whatisnumpy.html

> VanderPlas, J. (2016). Python Data Science Handbook (1st ed.). Sebastopol, California, United States of America: O’Reilly Media.

> VanderPlas, J. (2017, Junuary 5). Understanding Data Types in Python. Retrieved from github.com: https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.01-Understanding-Data-Types.ipynb